/**
 * Daily summary right-panel surface.
 *
 * The panel opens on the last day the environment recorded work, so a Monday
 * shows Friday rather than an empty Sunday. It generates only on an explicit
 * act: the first open of a day that has work and no stored summary, or the
 * Regenerate button. Stepping to another date shows what is stored there and
 * offers a button, so browsing history never spends provider tokens.
 *
 * The bullets are a list rather than a text box, so removing one, adding one
 * and reordering them do not need the model, and so a regeneration can honour
 * all three.
 */
import {
  DndContext,
  PointerSensor,
  closestCenter,
  useSensor,
  useSensors,
  type DragEndEvent,
} from "@dnd-kit/core";
import { restrictToParentElement, restrictToVerticalAxis } from "@dnd-kit/modifiers";
import { SortableContext, useSortable, verticalListSortingStrategy } from "@dnd-kit/sortable";
import { CSS } from "@dnd-kit/utilities";
import type { EnvironmentId, StandupItem } from "@t3tools/contracts";
import {
  ChevronLeft,
  ChevronRight,
  Copy,
  GripVertical,
  ListChecks,
  Plus,
  RefreshCw,
  Undo2,
  X,
} from "lucide-react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";

import { Button } from "~/components/ui/button";
import { ScrollArea } from "~/components/ui/scroll-area";
import { Tooltip, TooltipPopup, TooltipTrigger } from "~/components/ui/tooltip";
import { cn } from "~/lib/utils";
import { useStandup } from "~/state/standup";

const EMPTY_ITEMS: readonly StandupItem[] = [];

/** Steps a `YYYY-MM-DD` day, which is all the panel's arrows ever need. */
function shiftDay(day: string, delta: number): string {
  const [year = 0, month = 1, date = 1] = day.split("-").map(Number);
  return new Date(Date.UTC(year, month - 1, date + delta)).toISOString().slice(0, 10);
}

function formatDayLabel(day: string): string {
  const [year = 0, month = 1, date = 1] = day.split("-").map(Number);
  return new Date(Date.UTC(year, month - 1, date)).toLocaleDateString(undefined, {
    weekday: "short",
    day: "numeric",
    month: "short",
    timeZone: "UTC",
  });
}

function sameMembership(left: readonly StandupItem[], right: readonly StandupItem[]): boolean {
  if (left.length !== right.length) return false;
  const ids = new Set(left.map((item) => item.itemId));
  return right.every((item) => ids.has(item.itemId));
}

export function StandupPanel({ environmentId }: { environmentId: EnvironmentId | null }) {
  const standup = useStandup(environmentId);
  const { day, hasWork, summary, isLoading, isGenerating, generate } = standup;
  const [draft, setDraft] = useState("");
  const [copied, setCopied] = useState(false);
  /**
   * The order the user just dragged to, shown until the server echoes it.
   * Without it the list snaps back to the stored order for one round trip.
   */
  const [draggedOrder, setDraggedOrder] = useState<readonly StandupItem[] | null>(null);

  const serverItems = summary?.items ?? EMPTY_ITEMS;

  /**
   * A local order only survives while the same bullets are on screen. Adding,
   * removing or regenerating changes the membership, and the server's order is
   * then the only correct one.
   */
  const items = useMemo(() => {
    if (draggedOrder === null || !sameMembership(serverItems, draggedOrder)) return serverItems;
    const byId = new Map(serverItems.map((item) => [item.itemId, item]));
    return draggedOrder.map((item) => byId.get(item.itemId) ?? item);
  }, [draggedOrder, serverItems]);

  // One automatic generation per day, and only for a day that holds work and
  // has never been generated. Without the guard, a failed run would retry on
  // every render and spend tokens the user never asked for.
  const autoGeneratedDays = useRef(new Set<string>());
  useEffect(() => {
    if (day === null || summary !== null || !hasWork || isLoading || isGenerating) return;
    if (autoGeneratedDays.current.has(day)) return;
    autoGeneratedDays.current.add(day);
    void generate();
  }, [day, generate, hasWork, isGenerating, isLoading, summary]);

  const copy = useCallback(async () => {
    await navigator.clipboard.writeText(standup.text);
    await standup.save();
    setCopied(true);
  }, [standup]);

  useEffect(() => {
    if (!copied) return;
    const timer = setTimeout(() => setCopied(false), 2_000);
    return () => clearTimeout(timer);
  }, [copied]);

  // A short distance keeps a plain click on the handle from starting a drag,
  // and keeps the bullet text selectable.
  const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 6 } }));

  const handleDragEnd = useCallback(
    (event: DragEndEvent) => {
      const { active, over } = event;
      if (!over || active.id === over.id) return;
      const from = items.findIndex((item) => item.itemId === active.id);
      const to = items.findIndex((item) => item.itemId === over.id);
      if (from === -1 || to === -1) return;
      const next = [...items];
      const [moved] = next.splice(from, 1);
      if (!moved) return;
      next.splice(to, 0, moved);
      setDraggedOrder(next);
      void standup.reorderItems(next);
    },
    [items, standup],
  );

  const keptCount = items.filter((item) => !item.excluded).length;
  const sortableIds = useMemo(() => items.map((item) => item.itemId), [items]);

  return (
    <div className="flex h-full flex-col">
      <div className="flex shrink-0 items-center gap-1 border-b px-2 py-1.5">
        <Button
          variant="ghost"
          size="icon-sm"
          aria-label="Previous day"
          disabled={day === null}
          onClick={() => day !== null && standup.showDay(shiftDay(day, -1))}
        >
          <ChevronLeft className="size-4" />
        </Button>
        <span className="min-w-0 flex-1 truncate text-center font-medium text-sm">
          {day === null ? "No work recorded yet" : formatDayLabel(day)}
        </span>
        <Button
          variant="ghost"
          size="icon-sm"
          aria-label="Next day"
          disabled={day === null}
          onClick={() => day !== null && standup.showDay(shiftDay(day, 1))}
        >
          <ChevronRight className="size-4" />
        </Button>
        <Tooltip>
          <TooltipTrigger render={<span className="flex shrink-0" />}>
            <Button
              variant="ghost"
              size="icon-sm"
              aria-label="Regenerate the summary"
              disabled={day === null || isGenerating || !hasWork}
              onClick={() => void generate()}
            >
              <RefreshCw className={cn("size-4", isGenerating && "animate-spin")} />
            </Button>
          </TooltipTrigger>
          <TooltipPopup side="bottom">Regenerate the summary</TooltipPopup>
        </Tooltip>
      </div>

      <ScrollArea className="min-h-0 flex-1">
        <div className="flex flex-col gap-px p-2">
          {standup.error !== null ? (
            <p className="px-1 py-2 text-destructive text-sm">{standup.error}</p>
          ) : null}

          {isGenerating ? (
            <p className="px-1 py-2 text-muted-foreground text-sm">Reading the day's work...</p>
          ) : null}

          {!isGenerating && summary === null && day !== null ? (
            hasWork ? (
              <Button
                variant="secondary"
                size="sm"
                className="mt-1"
                onClick={() => void generate()}
              >
                <ListChecks className="size-4" />
                Write the summary for this day
              </Button>
            ) : (
              <p className="px-1 py-2 text-muted-foreground text-sm">
                Nothing was recorded on this day.
              </p>
            )
          ) : null}

          <DndContext
            sensors={sensors}
            collisionDetection={closestCenter}
            modifiers={[restrictToVerticalAxis, restrictToParentElement]}
            onDragEnd={handleDragEnd}
          >
            <SortableContext items={sortableIds} strategy={verticalListSortingStrategy}>
              {items.map((item) => (
                <StandupItemRow
                  key={item.itemId}
                  item={item}
                  onToggle={() => void standup.setItemExcluded(item.itemId, !item.excluded)}
                />
              ))}
            </SortableContext>
          </DndContext>
        </div>
      </ScrollArea>

      <div className="flex shrink-0 flex-col gap-2 border-t p-2">
        <form
          className="flex items-center gap-1"
          onSubmit={(event) => {
            event.preventDefault();
            void standup.addItem(draft);
            setDraft("");
          }}
        >
          <input
            className="min-w-0 flex-1 rounded-md border bg-transparent px-2 py-1.5 text-sm outline-none focus-visible:ring-1"
            placeholder="Add something the summary missed"
            value={draft}
            onChange={(event) => setDraft(event.target.value)}
          />
          <Button type="submit" variant="ghost" size="icon-sm" aria-label="Add this item">
            <Plus className="size-4" />
          </Button>
        </form>
        <Button variant="default" size="sm" disabled={keptCount === 0} onClick={() => void copy()}>
          <Copy className="size-4" />
          {copied ? "Copied" : `Copy ${keptCount} ${keptCount === 1 ? "bullet" : "bullets"}`}
        </Button>
      </div>
    </div>
  );
}

/**
 * One bullet.
 *
 * Drawn as a list row rather than a card: a border and a source line per bullet
 * made six items fill the panel, and the model's own source attribution was not
 * reliable enough to earn a line of its own.
 *
 * The grip and the remove button stay hidden until the row is hovered, so the
 * resting state reads as the text the user is about to paste. An excluded row
 * keeps its control visible, because a hidden way back is no way back.
 */
function StandupItemRow({ item, onToggle }: { item: StandupItem; onToggle: () => void }) {
  const { attributes, listeners, setNodeRef, transform, transition, isDragging } = useSortable({
    id: item.itemId,
  });

  return (
    <div
      ref={setNodeRef}
      style={{ transform: CSS.Translate.toString(transform), transition }}
      className={cn(
        "group flex items-start gap-1 rounded-md px-1 py-1 hover:bg-muted/50",
        isDragging && "z-10 bg-muted shadow-sm",
      )}
    >
      <button
        type="button"
        className={cn(
          "mt-0.5 shrink-0 cursor-grab rounded p-0.5 text-muted-foreground opacity-0 transition-opacity",
          "group-hover:opacity-100 focus-visible:opacity-100",
          isDragging && "cursor-grabbing opacity-100",
        )}
        aria-label="Reorder this item"
        {...attributes}
        {...listeners}
      >
        <GripVertical className="size-3.5" />
      </button>
      <span aria-hidden className="mt-[0.2rem] shrink-0 text-muted-foreground text-sm">
        &bull;
      </span>
      <p
        className={cn(
          "min-w-0 flex-1 text-sm leading-relaxed",
          item.excluded && "text-muted-foreground line-through",
        )}
      >
        {item.text}
      </p>
      <Button
        variant="ghost"
        size="icon-sm"
        className={cn(
          "shrink-0 opacity-0 transition-opacity group-hover:opacity-100 focus-visible:opacity-100",
          item.excluded && "opacity-100",
        )}
        aria-label={item.excluded ? "Put this item back" : "Leave this item out"}
        onClick={onToggle}
      >
        {item.excluded ? <Undo2 className="size-3.5" /> : <X className="size-3.5" />}
      </Button>
    </div>
  );
}
